services:
  - type: web
    name: shopping-backend
    runtime: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn shopping.wsgi:application"

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: DJANGO_SETTINGS_MODULE
        value: shopping.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: shopping-db
          property: connectionString

databases:
  - name: shopping-db
    databaseName: shopping
    plan: free
